#! /bin/bash

DOCKER_TOOLCHAIN_IMAGE="351elec/351elec-toolchain:latest"
SUDO=$(if ! docker ps -q 2> /dev/null 1> /dev/null; then echo "sudo"; fi)
DIR=./

${SUDO} docker pull ${DOCKER_TOOLCHAIN_IMAGE}

ID=$(${SUDO} docker create ${DOCKER_TOOLCHAIN_IMAGE})
function cleanup {
    ${SUDO} docker rm -f ${ID}
}
# Call the egress function
trap cleanup EXIT

echo "Copying arm ccache files..."
#${SUDO} docker cp ${ID}:/work/.ccache-arm/ ${DIR}
echo "Copying aarch64 files..."
#${SUDO} docker cp ${ID}:/work/.ccache-aarch64/ ${DIR}
for CURRENT_ARCH in arm aarch64; do
  for CURRENT_DEVICE in RG351P RG351V; do
    echo "Copying build files for ${CURRENT_DEVICE}:${CURRENT_ARCH}..."
    echo ${SUDO} docker cp ${ID}:/work/build.351ELEC-${CURRENT_DEVICE}.${CURRENT_ARCH} ${DIR}
  done
done