name: clean-pr
on:
  workflow_dispatch:
    inputs:
      clean_mode:
        description: 'Select clean target'
        required: true
        default: 'clean'
        type: choice
        options:
          - clean
          - clean-toolchain
          - distclean

jobs:
  build:
    runs-on: pr
    steps:
      - uses: actions/checkout@v7
        name: checkout
        with:
          clean: false
      - name: Clean Workspace
        run: |
          set -e
          make docker-${{ inputs.clean_mode }}